In [ ]:
!pip install yfinance

In [ ]:
import pandas as pd
import numpy as np
import math as math
import yfinance as yf

In [ ]:
from google.colab import files
files.upload()

In [ ]:
df = pd.read_csv('Nifty_50_Data.csv')
df.head(50)

Date          Open          High           Low         Close  \
0   2022-01-03  17387.150391  17646.650391  17383.300781  17625.699219   
1   2022-01-04  17681.400391  17827.599609  17593.550781  17805.250000   
2   2022-01-05  17820.099609  17944.699219  17748.849609  17925.250000   
3   2022-01-06  17768.500000  17797.949219  17655.550781  17745.900391   
4   2022-01-07  17797.599609  17905.000000  17704.550781  17812.699219   
5   2022-01-10  17913.300781  18017.449219  17879.150391  18003.300781   
6   2022-01-11  17997.750000  18081.250000  17964.400391  18055.750000   
7   2022-01-12  18170.400391  18227.949219  18128.800781  18212.349609   
8   2022-01-13  18257.000000  18272.250000  18163.800781  18257.800781   
9   2022-01-14  18185.000000  18286.949219  18119.650391  18255.750000   
10  2022-01-17  18235.650391  18321.550781  18228.750000  18308.099609   
11  2022-01-18  18337.199219  18350.949219  18085.900391  18113.050781   
12  2022-01-19  18129.199219  18129.199219  17884.900391  17938.400391   
13  2022-01-20  17921.000000  17943.699219  17648.449219  17757.000000   
14  2022-01-21  17613.699219  17707.599609  17485.849609  17617.150391   
15  2022-01-24  17575.150391  17599.400391  16997.849609  17149.099609   
16  2022-01-25  17001.550781  17309.150391  16836.800781  17277.949219   
17  2022-01-27  17062.000000  17182.500000  16866.750000  17110.150391   
18  2022-01-28  17208.300781  17373.500000  17077.099609  17101.949219   
19  2022-01-31  17301.050781  17410.000000  17264.150391  17339.849609   
20  2022-02-01  17529.449219  17622.400391  17244.550781  17576.849609   
21  2022-02-02  17706.199219  17794.599609  17674.800781  17780.000000   
22  2022-02-03  17767.750000  17781.150391  17511.150391  17560.199219   
23  2022-02-04  17590.199219  17617.800781  17462.550781  17516.300781   
24  2022-02-07  17456.300781  17536.750000  17119.400391  17213.599609   
25  2022-02-08  17279.849609  17306.449219  17043.650391  17266.750000   
26  2022-02-09  17370.099609  17477.150391  17339.000000  17463.800781   
27  2022-02-10  17554.099609  17639.449219  17427.150391  17605.849609   
28  2022-02-11  17451.000000  17454.750000  17303.000000  17374.750000   
29  2022-02-14  17076.150391  17099.500000  16809.650391  16842.800781   
30  2022-02-15  16933.250000  17375.000000  16839.250000  17352.449219   
31  2022-02-16  17408.449219  17490.599609  17257.699219  17322.199219   
32  2022-02-17  17396.550781  17442.900391  17235.849609  17304.599609   
33  2022-02-18  17236.050781  17380.800781  17219.199219  17276.300781   
34  2022-02-21  17192.250000  17351.050781  17070.699219  17206.650391   
35  2022-02-22  16847.949219  17148.550781  16843.800781  17092.199219   
36  2022-02-23  17194.500000  17220.699219  17027.849609  17063.250000   
37  2022-02-24  16548.900391  16705.250000  16203.250000  16247.950195   
38  2022-02-25  16515.650391  16748.800781  16478.300781  16658.400391   
39  2022-02-28  16481.599609  16815.900391  16356.299805  16793.900391   
40  2022-03-02  16593.099609  16678.500000  16478.650391  16605.949219   
41  2022-03-03  16723.199219  16768.949219  16442.949219  16498.050781   
42  2022-03-04  16339.450195  16456.000000  16133.799805  16245.349609   
43  2022-03-07  15867.950195  15944.599609  15711.450195  15863.150391   
44  2022-03-08  15747.750000  16028.750000  15671.450195  16013.450195   
45  2022-03-09  16078.000000  16418.050781  15990.000000  16345.349609   
46  2022-03-10  16757.099609  16757.300781  16447.900391  16594.900391   
47  2022-03-11  16528.800781  16694.400391  16470.900391  16630.449219   
48  2022-03-14  16633.699219  16887.949219  16606.500000  16871.300781   
49  2022-03-15  16900.650391  16927.750000  16555.000000  16663.000000   

       Adj Close  Volume  
0   17625.699219  200500  
1   17805.250000  247400  
2   17925.250000  251500  
3   17745.900391  236500  
4   17812.699219  239300  
5   18003.300781  232400  
6   18055.750000  220200  
7   18212.349609  2

In [ ]:
def volatility(df):
  df['volat'] = df['Adj Close'].pct_change()
  vol = df['volat'].std(ddof=0)*np.sqrt(252)
  return vol

In [ ]:
volatility(df)

0.17256999226747566

In [ ]:
df.head(50)

Date          Open          High           Low         Close  \
0   2022-01-03  17387.150391  17646.650391  17383.300781  17625.699219   
1   2022-01-04  17681.400391  17827.599609  17593.550781  17805.250000   
2   2022-01-05  17820.099609  17944.699219  17748.849609  17925.250000   
3   2022-01-06  17768.500000  17797.949219  17655.550781  17745.900391   
4   2022-01-07  17797.599609  17905.000000  17704.550781  17812.699219   
5   2022-01-10  17913.300781  18017.449219  17879.150391  18003.300781   
6   2022-01-11  17997.750000  18081.250000  17964.400391  18055.750000   
7   2022-01-12  18170.400391  18227.949219  18128.800781  18212.349609   
8   2022-01-13  18257.000000  18272.250000  18163.800781  18257.800781   
9   2022-01-14  18185.000000  18286.949219  18119.650391  18255.750000   
10  2022-01-17  18235.650391  18321.550781  18228.750000  18308.099609   
11  2022-01-18  18337.199219  18350.949219  18085.900391  18113.050781   
12  2022-01-19  18129.199219  18129.199219  17884.900391  17938.400391   
13  2022-01-20  17921.000000  17943.699219  17648.449219  17757.000000   
14  2022-01-21  17613.699219  17707.599609  17485.849609  17617.150391   
15  2022-01-24  17575.150391  17599.400391  16997.849609  17149.099609   
16  2022-01-25  17001.550781  17309.150391  16836.800781  17277.949219   
17  2022-01-27  17062.000000  17182.500000  16866.750000  17110.150391   
18  2022-01-28  17208.300781  17373.500000  17077.099609  17101.949219   
19  2022-01-31  17301.050781  17410.000000  17264.150391  17339.849609   
20  2022-02-01  17529.449219  17622.400391  17244.550781  17576.849609   
21  2022-02-02  17706.199219  17794.599609  17674.800781  17780.000000   
22  2022-02-03  17767.750000  17781.150391  17511.150391  17560.199219   
23  2022-02-04  17590.199219  17617.800781  17462.550781  17516.300781   
24  2022-02-07  17456.300781  17536.750000  17119.400391  17213.599609   
25  2022-02-08  17279.849609  17306.449219  17043.650391  17266.750000   
26  2022-02-09  17370.099609  17477.150391  17339.000000  17463.800781   
27  2022-02-10  17554.099609  17639.449219  17427.150391  17605.849609   
28  2022-02-11  17451.000000  17454.750000  17303.000000  17374.750000   
29  2022-02-14  17076.150391  17099.500000  16809.650391  16842.800781   
30  2022-02-15  16933.250000  17375.000000  16839.250000  17352.449219   
31  2022-02-16  17408.449219  17490.599609  17257.699219  17322.199219   
32  2022-02-17  17396.550781  17442.900391  17235.849609  17304.599609   
33  2022-02-18  17236.050781  17380.800781  17219.199219  17276.300781   
34  2022-02-21  17192.250000  17351.050781  17070.699219  17206.650391   
35  2022-02-22  16847.949219  17148.550781  16843.800781  17092.199219   
36  2022-02-23  17194.500000  17220.699219  17027.849609  17063.250000   
37  2022-02-24  16548.900391  16705.250000  16203.250000  16247.950195   
38  2022-02-25  16515.650391  16748.800781  16478.300781  16658.400391   
39  2022-02-28  16481.599609  16815.900391  16356.299805  16793.900391   
40  2022-03-02  16593.099609  16678.500000  16478.650391  16605.949219   
41  2022-03-03  16723.199219  16768.949219  16442.949219  16498.050781   
42  2022-03-04  16339.450195  16456.000000  16133.799805  16245.349609   
43  2022-03-07  15867.950195  15944.599609  15711.450195  15863.150391   
44  2022-03-08  15747.750000  16028.750000  15671.450195  16013.450195   
45  2022-03-09  16078.000000  16418.050781  15990.000000  16345.349609   
46  2022-03-10  16757.099609  16757.300781  16447.900391  16594.900391   
47  2022-03-11  16528.800781  16694.400391  16470.900391  16630.449219   
48  2022-03-14  16633.699219  16887.949219  16606.500000  16871.300781   
49  2022-03-15  16900.650391  16927.750000  16555.000000  16663.000000   

       Adj Close  Volume     volat  
0   17625.699219  200500       NaN  
1   17805.250000  247400  0.010187  
2   17925.250000  251500  0.006740  
3   17745.900391  236500 -0.010005  
4   17812.699219  239300  0.003764  
5   18003.300

In [ ]:
v = volatility(df)

In [ ]:
def alphaProbability(r,dt,v):
  u = np.exp(v*np.sqrt(dt))
  d = 1/u
  rnp = (np.exp(r*dt)-d)/(u-d)
  return rnp

In [ ]:
S = 17875

In [ ]:
def bopm(n,t,S,v):
  dt = t/n
  u = np.exp(v*np.sqrt(dt))
  d = 1/u
  Pm = np.zeros((n+1, n+1))
  for j in range(n+1):
    for i in range(j+1):
      Pm[i,j] = S*math.pow(d,i) * math.pow(u,j-i)
  return Pm

In [ ]:
n = 5
t = 200/365
v = volatility(df)
x = bopm(n,t,S,v)

print('n = 5:\n',np.matrix(x.astype(int)))

n = 5:
 [[17875 18925 20038 21216 22464 23784]
 [    0 16882 17875 18925 20038 21216]
 [    0     0 15945 16882 17874 18925]
 [    0     0     0 15059 15945 16882]
 [    0     0     0     0 14223 15059]
 [    0     0     0     0     0 13433]]


In [ ]:
def OptionsVal(n,S,k,r,v,T,PC):
  dt = T/n
  u = math.exp(v*math.sqrt(dt))
  d = 1/u
  p = (math.exp(r*dt)-d)/(u-d)
  Pm = np.zeros((n+1,n+1))
  Cm = np.zeros((n+1,n+1))
  tmp = np.zeros((2,n+1))
  for j in range(n+1):
    tmp[0,j] = S*math.pow(d,j)
    tmp[1,j] = S*math.pow(u,j)
  tot = np.unique(tmp)
  c = n
  for i in range(c+1):
    for j in range(c+1):
      Pm[i,j-c-1] = tot[(n-i)+j]
    c=c-1
  for j in range(n+1,0,-1):
    for i in range(j):
      if(PC == 1):
        if(j == n+1):
          Cm[i,j-1] = max(k-Pm[i,j-1],0)
        else:
          Cm[i,j-1] = math.exp(-r*dt)*(p*Cm[i,j] + (1-p)*Cm[i+1,j])
      if(PC == 0):
        if(j == n+1):
          Cm[i,j-1] = max(Pm[i,j-1]-k,0)
        else:
          Cm[i,j-1] = math.exp(-r*dt)*(p*Cm[i,j] + (1-p)*Cm[i+1,j])
  return [Pm,Cm]

In [ ]:
k = S
r = 0.06
T = 20/36
n = 10
PC = 0
Pm,CmC = OptionsVal(n,S,k,r,v,T,PC)
PC = 1
_,CmP = OptionsVal(n,S,k,r,v,T,PC)
print('Pricing:\n',np.matrix(Pm.astype(int)))
print('Call Option:\n',np.matrix(CmC.astype(int)))
print('Put Option:\n',np.matrix(CmP.astype(int)))

Pricing:
 [[17875 18617 19389 20194 21033 21906 22815 23762 24749 25776 26847]
 [    0 17162 17875 18617 19389 20194 21033 21906 22815 23762 24749]
 [    0     0 16478 17162 17875 18617 19389 20194 21033 21906 22815]
 [    0     0     0 15821 16478 17162 17875 18617 19389 20194 21033]
 [    0     0     0     0 15190 15821 16478 17162 17875 18617 19389]
 [    0     0     0     0     0 14585 15190 15821 16478 17162 17875]
 [    0     0     0     0     0     0 14004 14585 15190 15821 16478]
 [    0     0     0     0     0     0     0 13445 14004 14585 15190]
 [    0     0     0     0     0     0     0     0 12909 13445 14004]
 [    0     0     0     0     0     0     0     0     0 12395 12909]
 [    0     0     0     0     0     0     0     0     0     0 11901]]
Call Option:
 [[1201 1631 2164 2799 3526 4326 5177 6065 6993 7961 8972]
 [   0  723 1040 1460 1995 2646 3394 4209 5059 5947 6874]
 [   0    0  370  572  865 1274 1818 2497 3277 4090 4940]
 [   0    0    0  145  245  408  667 1062 